/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectAppealStatusCode } from '../models/project-appeal-status-code';
import { ProjectEligibilityAppeal } from '../models/project-eligibility-appeal';
import { StateCode } from '../models/state-code';
export interface ProjectAppeal {
  aarAdditionalInfoRequest?: boolean | null;
  aarCheckLgOrIgbAppealDecisionLetter?: boolean | null;
  aarRequiresDecisionNote?: boolean | null;
  aarWaitingOnLegal?: boolean | null;
  accAdditionaInfoRequested?: boolean | null;
  accBackupDocuments?: boolean | null;
  accCheckLgOrIgbAppealDecisionLetter?: boolean | null;
  accEligibleProjectScope?: boolean | null;
  accIcrpSpreadsheetComplete?: boolean | null;
  accPreExistingCondition?: boolean | null;
  accStampAllDocuments?: boolean | null;
  accTimelineNoteAdded?: boolean | null;
  additionalInfoRequested?: boolean | null;
  apAdditionalInfoRequest?: boolean | null;
  apRequiresDecisionNote?: boolean | null;
  apWaitingOnLegal?: boolean | null;
  appealDecision?: string | null;
  appealDecisionCommentsAdded?: boolean | null;
  assignedToAdjudicator?: boolean | null;
  assignedToEvaluator?: boolean | null;
  backUpDocuments?: boolean | null;
  caseMaterialsReviewed?: boolean | null;
  checkLgOrIgbAppealDecisionLetter?: boolean | null;
  eligibleProjectScope?: boolean | null;
  generateAppealDecisionLetter?: boolean | null;
  icrpSpeadSheetComplete?: boolean | null;
  id?: string;
  inEApprovals?: boolean | null;
  name?: string;
  preExistingCondition?: boolean | null;
  projectAppealEligibility?: ProjectEligibilityAppeal | null;
  projectId?: string;
  requiresDecisionNote?: boolean | null;
  reviewAppealDecisionLetter?: boolean | null;
  stampAllDocuments?: boolean | null;
  stateCode?: StateCode;
  statusCode?: ProjectAppealStatusCode | null;
  submittedForDirectorReview?: boolean | null;
  timelineNoteAdded?: boolean | null;
  updateProjectApprovedCosts?: boolean | null;
  updateProjectDecision?: boolean | null;
  waitingOnLegal?: boolean | null;
}
