describe("DFA Public Sector", () => {
  it("tests DFA Public Sector", () => {
    cy.viewport(2505, 1316);
    cy.visit("https://publicsector-dev.dfa.gov.bc.ca/registration-method");
    cy.get("span.mdc-button__label").click();
    cy.origin("publicsector-dev.dfa.gov.bc.ca", () => {
      cy.url().should("contain", "dev.loginproxy.gov.bc.ca/auth/realms/bc");
      cy.get("#user").click();
      cy.get("#user").type("");
      cy.get("#password").click();
      cy.get("#password").type("");
      cy.get("div.login-form-action > input").click();
    });
    cy.location("href").should("eq", "https://logontest7.gov.bc.ca/clp-cgi/preLogon.cgi");
    cy.get("main span.mdc-button__label").click();
    cy.get("#mat-input-6").click();
    cy.get("form > div:nth-of-type(2) > div:nth-of-type(1) span.mat-mdc-button-touch-target").click();
    cy.get("button.mat-calendar-previous-button > span.mat-mdc-focus-indicator").click();
    cy.get("tr:nth-of-type(1) span.mat-calendar-body-cell-content").click();
    cy.get("#cdk-step-content-0-0 div:nth-of-type(2) > div:nth-of-type(2)").click();
    cy.get("#cdk-step-content-0-0 div:nth-of-type(2) > div:nth-of-type(2) span.mat-mdc-button-touch-target").click();
    cy.get("tr:nth-of-type(5) > td:nth-of-type(3) span.mat-calendar-body-cell-content").click();
    cy.get("#mat-select-value-1").click();
    cy.get("#mat-option-5 > span").click();
    cy.get("#mat-mdc-checkbox-1-input").click();
    cy.get("#mat-select-value-3").click();
    cy.get("#mat-option-1").click();
    cy.get("#cdk-step-content-0-0 > div:nth-of-type(1) > div:nth-of-type(2) span.mdc-button__label").click();
    cy.get("app-bc-address > div > div:nth-of-type(1) div.mat-mdc-form-field-infix").click();
    cy.get("#mat-input-26").click();
    cy.get("#mat-input-26").type("100 Mile House");
    cy.get("#mat-input-22").click();
    cy.get("#mat-input-22").type("1");
    cy.get("#mat-option-7 > span").click();
    cy.get("form.ng-untouched span.mdc-button__label").click();
    cy.get("#mat-input-29").click();
    cy.get("#mat-input-29").type("S");
    cy.get("#mat-input-29").type("Seamus");
    cy.get("#mat-input-30").type("tester");
    cy.get("#mat-input-31").type("(250) 123-4567");
    cy.get("#mat-input-32").type("test@");
    cy.get("#mat-input-32").type("test@test.com");
    cy.get("div:nth-of-type(4) > div:nth-of-type(2) span.mdc-button__label").click();
    cy.get("mat-card > div:nth-of-type(2) > div:nth-of-type(1) div.mat-mdc-form-field-infix").click();
    cy.get("#mat-input-33").type("(250) 123-4567");
    cy.get("#mat-input-34").click();
    cy.get("#mat-input-34").type("title");
    cy.get("div:nth-of-type(4) > div:nth-of-type(2) span.mat-mdc-button-touch-target").click();
    cy.get("#mat-radio-9-input").click();
    cy.get("#cdk-step-content-0-1 > div:nth-of-type(1) > div:nth-of-type(2) span.mdc-button__label").click();
    cy.get("div:nth-of-type(2) > div > div:nth-of-type(1) > div:nth-of-type(1) div.mat-mdc-form-field-infix").click();
    cy.get("#mat-input-0").type("W");
    cy.get("#mat-input-0").type("Wayne");
    cy.get("#mat-input-1").type("P");
    cy.get("#mat-input-1").type("Peters2");
    cy.get("#mat-input-2").type("(444) 444-4444");
    cy.get("#mat-input-3").type("wayne");
    cy.get("#mat-input-3").type("wayne.peters@");
    cy.get("#mat-input-3").type("wayne.peters@nttdata.com");
    cy.get("#mat-input-4").type("title");
    cy.get("#mat-radio-3-input").click();
    cy.get("#mat-radio-6-input").click();
    cy.get("#cdk-step-content-0-2 > div > div.ng-star-inserted span.mdc-button__label > span").click();
    cy.get("mat-dialog-actions > div:nth-of-type(2) span.mdc-button__label").click();
    cy.get("div.cdk-overlay-container span.mat-mdc-button-touch-target").click();
  });
});
